import React, { useState } from "react";
import Button from "@mui/material/Button";
import TextField from "@mui/material/TextField";
import InstagramIcon from "@mui/icons-material/Instagram";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import GoogleLoginButton from "./GoogleLoginButton";

const LoginPage = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");

  const handleInstagramLogin = () => {
    const clientId = "584458130551150"; //Instagram App ID
    const redirectUri = "https://bc11-192-155-83-140.ngrok-free.app"; //public url represent http://localhost:3000 generated by ngrok

    const url = `https://api.instagram.com/oauth/authorize
      ?client_id=${clientId}
      &redirect_uri=${redirectUri}
      &scope=user_profile,user_media
      &response_type=code`;

    window.location.href = url;
  };

  // handle login with username and password
  const handleLogin = (event) => {
    event.preventDefault();
    console.log("Logging in with username and password");
  };

  return (
    <Container maxWidth="sm">
      <Box sx={{ mt: 7, mb: 3 }}>
        <Typography variant="h4" component="h1" gutterBottom>
          Log In
        </Typography>
      </Box>

      {/* Google login */}
      <GoogleLoginButton />

      <Box sx={{ mt: 2 }} />

      {/* Instagram SSO */}
      <Button
        variant="outlined"
        startIcon={<InstagramIcon />}
        onClick={handleInstagramLogin}
        fullWidth
      >
        Sign up with Instagram
      </Button>

      <Box sx={{ mt: 3, mb: 3 }}>
        <Typography variant="body1" component="p" gutterBottom>
          Or Sign in with
        </Typography>
      </Box>

      {/* username and password login */}
      <form onSubmit={handleLogin}>
        <TextField
          label="Username"
          fullWidth
          value={username}
          onChange={(e) => setUsername(e.target.value)}
        />

        <Box sx={{ mt: 2 }} />

        <TextField
          label="Password"
          fullWidth
          type="password"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
        />

        <Box sx={{ mt: 2 }} />

        <Button variant="contained" type="submit" fullWidth>
          Sign in
        </Button>
      </form>
    </Container>
  );
};

export default LoginPage;
